###create movie
POST localhost:8080/movie/create
Content-Type: application/json

{
  "title": "Inception",
  "genre": "Sci-Fi",
  "releaseYear": "2010",
  "createdBy": 1
}

###create movie
POST localhost:8080/movie/create
Content-Type: application/json

{
  "title": "The Dark Knight",
  "genre": "Action",
  "releaseYear": "2008",
  "createdBy": 0
}

###create movie
POST localhost:8080/movie/create
Content-Type: application/json

{
  "title": "Interstellar",
  "genre": "Adventure",
  "releaseYear": "2014",
  "createdBy": 2
}

###create movie
POST localhost:8080/movie/create
Content-Type: application/json

{
  "title": "Pulp Fiction",
  "genre": "Crime",
  "releaseYear": "1994",
  "createdBy": 1
}

###create movie
POST localhost:8080/movie/create
Content-Type: application/json

{
  "title": "The Matrix",
  "genre": "Action",
  "releaseYear": "1999",
  "createdBy": 0
}

###get movie list
GET localhost:8080/movie/list

###get movie by id
GET localhost:8080/movie/by-id/1

###delete movie
DELETE localhost:8080/movie/delete/2

###search
GET localhost:8080/movie/search/Act

###get top 5 movies
GET localhost:8080/movie/top



