###create review
POST localhost:8080/reviews/create
Content-Type: application/json

{
  "userId": 0,
  "movieId": 4,
  "rating": 4.50,
  "comment": "Ajoyib film, syujeti juda qiziqarli ekan."
}

###create review
POST localhost:8080/reviews/create
Content-Type: application/json

{
  "userId": 2,
  "movieId": 1,
  "rating": 5.0,
  "comment": "Menga juda yoqdi, hammaga tavsiya qilaman!"
}


###create review
POST localhost:8080/reviews/create
Content-Type: application/json

{
  "userId": 1,
  "movieId": 0,
  "rating": 3.2,
  "comment": "Yaxshi, lekin ba'zi joylari tushunarsiz qolgan."
}

###create review
POST localhost:8080/reviews/create
Content-Type: application/json

{
  "userId": 0,
  "movieId": 2,
  "rating": 4.8,
  "comment": "Vizual effektlar va musiqa a'lo darajada."
}

###create review
POST localhost:8080/reviews/create
Content-Type: application/json

{
  "userId": 2,
  "movieId": 3,
  "rating": 2.5,
  "comment": "Kutilganidek chiqmadi, vaqt sarflashga arzimaydi."
}

###create review
POST localhost:8080/reviews/create
Content-Type: application/json

{
  "userId": 1,
  "movieId": 4,
  "rating": 4.0,
  "comment": "Aktyorlar mahorati yuqori darajada ekan."
}

###create review
POST localhost:8080/reviews/create
Content-Type: application/json

{
  "userId": 0,
  "movieId": 1,
  "rating": 1.5,
  "comment": "Zerikarli film, oxirigacha ko'ra olmadim."
}

###create review
POST localhost:8080/reviews/create
Content-Type: application/json

{
  "userId": 2,
  "movieId": 0,
  "rating": 3.80,
  "comment": "O'rtacha film, bir marta ko'rish uchun yomon emas."
}

###create review
POST localhost:8080/reviews/create
Content-Type: application/json

{
  "userId": 1,
  "movieId": 2,
  "rating": 4.20,
  "comment": "Mantiqiy yechimlar juda yaxshi o'ylangan."
}

###create review
POST localhost:8080/reviews/create
Content-Type: application/json

{
  "userId": 0,
  "movieId": 3,
  "rating": 5.0,
  "comment": "Shubhasiz, yilning eng yaxshi filmlaridan biri!"
}

###get movie review
GET localhost:8080/reviews/by-movie-id/2
